version: '3.8'

services:
  app:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0
    depends_on:
      - grownomics-db

  grownomics-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: grownomics_db
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
