name: Backend Tests

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      grownomics-db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_DB: grownomics_db
        ports:
          - 5432:5432
        # Opciones adicionales para asegurar que la base de datos esté lista
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Set up Database URL
      run: echo "SQLALCHEMY_DATABASE_URI=postgresql://postgres:example@localhost:5432/grownomics_db" > .env
    
    - name: Run Tests
      run: |
        cd backend
        python -m pytest tests/
