name: Backend Tests

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_DB: grownomics_db
        ports:
          - 5432:5432
        options: >-
          -v /home/runner/work/Proyecto-Informatica/Proyecto-Informatica/backend/backup.sql:/docker-entrypoint-initdb.d/backup.sql

    steps:
    - uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Set up Docker Compose
      run: docker-compose -f backend/docker-compose.yml up -d

    - name: Wait for DB to be ready
      run: |
        until docker exec $(docker-compose -f backend/docker-compose.yml ps -q grownomics-db) pg_isready ; do sleep 5 ; done

    - name: Run Tests
      run: docker-compose -f backend/docker-compose.yml exec -T app python -m pytest tests/
