name: Flutter Tests

on:
  push:
    branches:
      - main
    paths:
      - 'grownomics/**'
  pull_request:
    branches:
      - main
    paths:
      - 'grownomics/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'

    - name: Install Dependencies
      run: |
        cd grownomics
        flutter pub get

    - name: Run Flutter Tests
      run: |
        cd grownomics
        flutter test
